V5 padding extension
pendulum-project/ntpd-rs pull request #1169
Opened 2023-10-31 20:27 UTC by marlonbaeten

2023-11-01 08:31 UTC, tdittr reviewed
Not sure if this is the way to go, as callinf `.append_padding()` before serializing could break stuff. I think we need to further discuss this and see what is a good solution.

2023-11-01 08:31 UTC, tdittr commented on ntp-proto/src/packet/extension_fields.rs
> +    pub fn byte_length(&self) -> usize {
```suggestion
    pub fn wire_length(&self) -> usize {
```

2023-11-01 08:31 UTC, tdittr commented on ntp-proto/src/packet/mod.rs
> +    pub fn byte_length(&self) -> usize {
```suggestion
    pub fn wire_length(&self) -> usize {
```

2023-11-01 08:31 UTC, tdittr commented on ntp-proto/src/packet/mod.rs
> +                .map(|ev| ev.byte_length())
```suggestion
                .map(|ev| ev.wire_length())
```

2023-11-01 08:49 UTC, davidv1992 commented
Honestly, I think a better approach is to not add this as an actual extension field before serialization, but rather to generate this as needed during serialization.

2023-11-02 09:06 UTC, tdittr requested changes

2023-11-02 09:06 UTC, tdittr commented on ntp-proto/src/packet/mod.rs
> +            desired_size: Some(desired_size),
Having this in the header feels weird, why not pass the length to the call, or specify that the buffer we write to should be the same size as the request packet?

2023-11-04 09:20 UTC, tdittr approved these changes
Looks good! Much cleaner

2023-11-04 10:04 UTC, davidv1992 approved these changes

2023-11-04 10:05 UTC, merged