Pedantic linting
pendulum-project/ntpd-rs pull request #1679
Opened 2024-10-12 18:07 UTC by van-sprundel

- [x] nts-pool-ke
- [ ] ntp-proto
- [x] ntpd

Fixes #1658.

There are some opinionated changes here, so feel free to call out anything that's not wanted.
All changes are first ran with `cargo clippy --fix -p [project]`, and I've left out `clippy::module_name_repetitions` as it doesn't add much here.

Some notable lints from the pedantic group:
- `ntpd::ctl::NtpCtlOptions` now uses the `action` state instead of bools
- Some `match` cases became `if () { } else { }` where relevant
- Some `let foo = if foo() else { } became `let Some(...} = foo() else {}` where relevant
- `async` and `Result<_>` are removed on places where it wasn't used and relevant
- `const` and `enum` mid-function are moved up at the beginning of the function, or moved up a scope
- `ntpd::daemon:;ntp_source::SourceTask::run` has been split up into multiple functions
- Conversions that could truncate or lose sign are marked as allowed where relevant.

2024-10-16 08:36 UTC, davidv1992 requested changes
Thank you for picking this up. The changes make very clear that this was a good idea, even though it will still be some work to fully get these changes to land. Below I have made a number of comments. Note that most of these are notes to ourselves that we need to improve code in some places more and those need not be blockers for landing this in my eyes. I have marked those that do require more attention.

Please also note that given the wide scope of these changes, I am not comfortable merging these only on my opinion, so once this is further along there is going to be a review by a second person.

Again, thank you for doing the legwork on this. By the looks of it, you saved us quite some work. I hope you can bear with us while we make the push to get this in reviewable enough to merge it.

2024-10-16 08:36 UTC, davidv1992 commented on ntp-proto/src/nts_record.rs
> +    /// Returns error if getting the TLS bool `wants_write` fails.
Doesn't actually return an error

2024-10-16 08:36 UTC, davidv1992 commented on ntp-proto/src/nts_record.rs
> -
Same as above, please split these refactors into a separate PR

2024-10-16 08:36 UTC, davidv1992 commented on ntp-proto/src/nts_record.rs
> +    /// Returns error if getting the TLS bool `wants_write` fails.
Doesn't actually error

2024-10-16 08:36 UTC, davidv1992 commented on ntp-proto/src/packet/extension_fields.rs
> +#![allow(clippy::cast_possible_truncation)]
Note to self: Eliminate here, too general

2024-10-16 08:36 UTC, davidv1992 commented on ntp-proto/src/packet/mod.rs
> -                    NtpPacket {
Good refactor on this match, but again needs more involved review. Could you please make this a separate PR?

2024-10-16 08:36 UTC, davidv1992 commented on ntpd/src/ctl.rs
> -    }
Needs fix: it is actually quite subtle, but removing this, in combination with the changes above, actually changes behaviour, and in an unwanted way. In particular, it changes behaviour of the -v and -h flags overriding all other actions, which is undesired. Please revert.

2024-10-16 08:36 UTC, davidv1992 commented on ntpd/src/daemon/ntp_source.rs
> -                                        "we received a message without having sent one; discarding"
Needs fix: Again, this is likely (part of) a good refactor, but too hard to review well in this context, please split this off into a separate PR.

2024-10-16 08:38 UTC, davidv1992 commented
@rnijveld As a headsup, just so you are aware of this PR, I am going to ask you to review this once it is a bit further along. Most of it is relatively straightforward, and hopefully we can split the parts that aren't into separate PRs. It does highlight a few places to where we should probably take a second look at code, particularly around casts.

2024-11-20 15:01 UTC, van-sprundel commented
Sorry for the radio silence, I'll take a look at the review and rebase the PR.

Am I safe to assume that all the reviews without "note to self" are something I can refactor?

2024-11-28 07:25 UTC, davidv1992 commented
Yes, those are things that need attention before this can move forward.

2025-01-09 16:09 UTC, van-sprundel commented
While refactoring I did found that `test_deny_stops_poll` will not always succeed (even on main). Seems like a timing issue. Could it be that the cast to u32 is causing this?

https://github.com/pendulum-project/ntpd-rs/blob/419832f28b8560ae44fb178e54d2ba6328cc6da0/ntpd/src/daemon/ntp_source.rs#L541-L548

or something in the test startup that's failing it? my initial changes made it always fail, but now it sometimes fails on main

```sh
cargo test test_deny_stops_poll --target x86_64-unknown-linux-gnu --features run_tokio_rustls_tests
```

2025-01-09 16:20 UTC, van-sprundel commented on ntpd/src/ctl.rs
> -    }
Seems like this was refactored in-between time, nice

2025-01-09 16:20 UTC, van-sprundel commented on ntp-proto/src/packet/mod.rs
> -                    NtpPacket {
Refactored already, looks good!

2025-02-07 08:09 UTC, cikzh commented
Thank you for great work! It looks like we severely underestimated this being a good first issue and the impact it would have. I've discussed this with @rnijveld and @davidv1992 and we think the best way forward is to hack this PR up into smaller, better reviewable chunks, so we can evaluate them piece-by-piece. Also, given the time this ended up taking, it will be easier to stay up-to-date with `main` that way.

We've created a tracking issue (#1818), so we can track the progress and manage the workload. If some commits of this branch are easily cherry-pickable into seperate PR's, we'd appreciate the help!

2025-06-19 09:04 UTC, rnijveld commented
Closing this PR for now as explained previously :)

2025-06-19 09:04 UTC, closed without merging