stop sending messages to servers that send the DENY code
pendulum-project/ntpd-rs pull request #91
Opened 2022-05-13 13:59 UTC by folkertdev

we did previously remove a peer that receives DENY from the list of peers, but did not cancel the task that keeps sending messages to the server. Also the ordering of checks was such that the KISS code would never be processed if other fields of the packet are also invalid. But the spec notes that if a KISS code is sent, the rest of the packet may be invalid anyway. So we should check for kiss codes first when validating a packet.

2022-05-13 14:15 UTC, folkertdev commented on ntp-daemon/src/peer.rs
> -                                    Ok(update) => {
the diff here is not great. what I'm doing is inverting the control flow: we now check the `result` before checking whether we should `accept_synchronization`. In particular that means the DENY kiss code is now correctly propagated

2022-05-13 14:15 UTC, folkertdev commented on ntp-daemon/src/peer.rs
> -                                        let _ = tx.send(MsgForSystem::MustDemobilize);
this was unreachable before because a packet with a kiss code would never be accepeted

2022-05-13 14:15 UTC, folkertdev commented on ntp-proto/src/peer.rs
> +        if message.is_kiss_rate() {
messages with a kiss code make no guarantees about the other fields, but we still must respect the kiss codes. So, check the kiss codes first

2022-05-13 15:45 UTC, davidv1992 commented
The merge conflict here are such that it is hard to currently judge the desired end state. Could you resolve these?

2022-05-17 06:45 UTC, davidv1992 requested changes
Mostly looks good, and it is important that we start testing these sort of things. However, I am not convinced we should make the test server part of the main ntp-daemon package. I think it is cleaner from an auditability standpoint to isolate these in their own package, despite the ergonomic cost.

2022-05-17 06:45 UTC, davidv1992 commented on ntp-proto/src/identifiers.rs
> +    pub fn from_int(value: u32) -> ReferenceId {
Given that we make the constants public, why does this then also need to be pub?

2022-05-17 06:45 UTC, davidv1992 commented on ntp-proto/src/identifiers.rs
> +    pub(crate) const KISS_RSTR: Self = ReferenceId(0x52535452);
I would suggest that if we make one public, we make em all public

2022-05-17 06:45 UTC, davidv1992 commented on README.md
> +runs an NTP server on port `8080` that always responds with the DENY kiss code. It is used to test
Nit: I would formulate this as it can be used instead of is used, since we don't use it in automated tests.

2022-05-24 07:46 UTC, folkertdev commented on ntp-daemon/src/peer.rs
> +        match result {
bit of a crappy diff, but this inverts the matches: now we first check the result, do something with the kiss code if needed, then look at whether the message is accepted.

2022-05-24 07:46 UTC, folkertdev commented on ntp-proto/src/identifiers.rs
> +    pub const KISS_RSTR: ReferenceId = ReferenceId(u32::from_be_bytes(*b"RSTR"));
makes this much more readable I think

2022-05-24 07:46 UTC, folkertdev commented on ntp-proto/src/peer.rs
> +        if message.is_kiss_rate() {
kiss codes must be handled first, because there are no guarantees about any of the other fields in the packet if a kiss code is set.

2022-05-24 07:46 UTC, folkertdev commented on test-binaries/src/bin/rate-limit-server.rs
> +            packet.transmit_timestamp = clock.now().unwrap();
NTP server: done

2022-05-24 14:59 UTC, merged